### ISSUE TITLE
postgresql role fails

### ISSUE THREAD

**Issue by DerDanilo** [citronalco/ansible-nsupdate.info#2]
The roles fails to execute the module tasks. It may be related to the fact that I am accessing the server via a user that that has to sudo every command. Therefore the command that has to sudo into postgres fails.

```
fatal: [ddns01]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chmod: invalid mode: ‘A+user:postgres:rx:allow’\nTry 'chmod --help' for more information.\n}). For information on working around this, see https://docs.ansible.com/ansible-core/2.12/user_guide/become.html#risks-of-becoming-an-unprivileged-user"}
```

I created the db and user via cli but it would be nice if the role actually works.

Thanks

**Comment by citronalco** [comment]
This is are quite uncommon conditions, and I'm not actively using this playbook anymore. So I won't fix it. You may fork it if you want.

It was planned to be used for a hacker space. Testing was successful, but it was decided not to offer this service for other reasons.
If you're offering such a service to others: Users might get problems when creating letsencrypt certs at some point, because letsencrypt only issue a limited number of certs per (sub)domain in a given time. There are several ways around that, but I have not tried them.
